repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        exclude_types: [csv]
      - id: trailing-whitespace
        exclude_types: [csv]
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-ast
      - id: no-commit-to-branch
        args: [--branch, master]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
      - id: ruff-format
